.github/workflows/lint.yml

Realized in https://github.com/transitmatters/gobble/pull/9 we added Python 3.11 to the `pyproject.toml` but not the lint action

Add Python 3.11 to lint matrix

---

devops/cloudformation.json
devops/playbook.yml
src/gtfs.py
src/s3_upload.py

Gotta write bugs to fix bugs, thanks @devinmatte for the ansible fixes. Commandeering this draft https://github.com/transitmatters/gobble/pull/15.
Gobble was crashing on a URL pull (see stack trace,) turns out `pathlib` will truncate all instances of multiple slashes. Switching that to a regular slash--should make the service happier. 
```
ubuntu@ip-172-31-45-145:~$ journalctl --since "2023-12-07 17:13:00"
Dec 07 17:13:00 ip-172-31-45-145 poetry[138534]: Downloading GTFS bundle if necessary...
Dec 07 17:13:00 ip-172-31-45-145 poetry[138534]: No matches found in existing GTFS archives. Fetching latest archives.
Dec 07 17:13:00 ip-172-31-45-145 poetry[138534]: Traceback (most recent call last):
Dec 07 17:13:00 ip-172-31-45-145 poetry[138534]:   File "/home/ubuntu/gobble/src/gobble.py", line …
```

Some fixes to the cron job

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
pyproject.toml

Fixing the deploy so that we properly access the DD_API_KEY (oops)
Also deploy happens on Python 3.12, so we should lint on 3.12 as well

Fixing the deploy and linting for 3.12

---

src/gtfs.py

The GTFS stop times dataframe can take as much as >1.2 gigs in memory if we pull all of it (varies per gtfs package.)The actual `.txt` it's based off of only needs ~160 MB 🙃 
Only reading in the useful columns takes our usage down from 1.2 gigs to ~0.86, and is filtered down to an eighth of that after later filtering. 
**We might need to shrink this usage down even further later on: an approach here if we keep OOM-ing would be to first stream through the file with a more lightweight file reader, identify the # rows which contain the trips we care about, then feed those rows indices into the `skiprows` arg. Is this a nightmare? Is pandas a nightmare? Are we in a nightmare?

Only pull relevant columns from gtfs stops

---

src/disk.py
src/gobble.py

Current state file is truncated--we shouldn't attempt to load a file like this when this happens, and not loading it won't degrade the service. Will also try to find out whats going on there.

Skip loading state if JSON is corrupted

---

devops/playbook.yml

a saucy pr for a saucy crontab
also a fun TIL: running `env -i /bin/bash --noprofile --norc` will give you the same env that `cron` uses

make explicit poetry

---

devops/playbook.yml

EC2 only had 3.10, we should actually install 3.11 with ansible

Actually install python 3.11

---

src/s3_upload.py

theres some GMT/date math which can result in data from a new day being lost--do this to pull data from the past more conservatively in the s3 upload cron job

look 45 min in the past for a 30 min cron job

---

src/gobble.py

Use the `current_status` signal to capture arrivals so that we can keep track of dwell times and travel times in addition to headways. (Note that this isn't a problem for scheduled headways b/c the schedule doesn't distinguish arrival and departure times.)
Ran it for a couple of single trips with some aggressive logging to yield something like this...
```
INFO:repos/gobble/src/gobble.py:60168633 current_stop_sequence: 3: STOPPED_AT    | stop: 2, prev: 1
INFO:repos/gobble/src/gobble.py:60168633 current_stop_sequence: 4: IN_TRANSIT_TO | stop: 6, prev: 2
INFO:repos/gobble/src/gobble.py:60168633 current_stop_sequence: 4: STOPPED_AT    | stop: 6, prev: 6
INFO:repos/gobble/src/gobble.py:60168633 current_stop_sequence: 5: IN_TRANSIT_TO | stop: 10003, prev: 6 …
```

intuit arrivals from v3 api

---

src/disk.py
src/gobble.py
src/gtfs.py
src/s3_upload.py
src/util.py

various date changes!
1. we were looks at current date, not service date, for data uploads. for s3 upload jobs run between midnight and 4am, we should be looking to the previous day etc. 
2. the realtime API reports local time, whereas the monthly MBTA CSV's are in UTC. we'll convert the gobble event times to UTC as well. 
3. also a couple more type annos because we love our future selves.
fun fact! its call `tz_convert` because you feel like youve been taken to the twilight zone <3

use service date for s3 uploads, save as UTC

---

.gitignore
devops/deploy.sh
devops/playbook.yml
devops/systemd.conf
poetry.lock
pyproject.toml
src/gobble.py
src/logger.py
src/s3_upload.py

Wanted to get logging into Datadog so we can more easily track down issues and see logs without checking the server
Also saves it to a file so we don't lose logs when things die
See on Datadog how it would look: https://app.datadoghq.com/logs?query=service%3Agobble%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1704758723000&to_ts=1704759023000&live=true
Allowing filters, for example, only logs for the 28: https://app.datadoghq.com/logs?query=service%3Agobble%20%40route%3A28&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1704758723000&to_ts=1704759023000&live=true

Adds logging in a format that datadog can read

---

devops/playbook.yml

Sometimes when testing changes, I'd deploy a branch. So when the redeploy happens in CI, it doesn't return to main. We should ensure deploys happen from the main branch

Always use `main` for deployments

---

src/constants.py
src/event.py
src/gobble.py
src/util.py

adding rapid transit to gobble ingests real quick. you can peep sample data uploaded via `s3_upload.py` at `s3://tm-mbta-performance/Events-live/daily-rapid-data/`
some notes:
* we store event info for all stops on all subway lines. is there a subset we should be using instead?
* note that the s3 file structure doesnt match that of the performance API s3 data: general structure is something like `Events-live/daily-rapid-data/Green-B_0_70117/Year=...`
* The Union Square GL has a weird stop ID that introduces spaces into the s3 path, zoinks scoob

add rapid transit to gobble

---

src/event.py

just a small one: we're doubling up error logs, which makes it slightly annoying to go through them on datadog. also properly stringifying the update dicts so dd can parse them.

consolidate quality checks for stop id

---

src/disk.py
src/event.py
src/gtfs.py

each logger needs to be configured on a per-file basis. so does ddtracing--disabling that locally as well.

configure loggers across all files explicitly 

---

devops/deploy.sh

Today we manually restarted the EC2 instance assigned to Gobble and it got a new public Internet address.
This breaks our deploy script because it's reading from `aws cloudformation describe-stacks` which contains the output from CloudFormation when it originally queried the instance. If we want, we can get the current instance address like this:
- Look up the physical ID of the EC2 instance by its logical ID (which is statically known from `cloudformation.json`)
- Look up the DNS address of the instance by physical ID
_Test plan:_
I ran `deploy.sh` locally and verified that it was able to connect to the EC2 instance (well, uh, _an_ EC2 instance). We'll probably have to try it on GH Actions to be 100% sure.

fix: Always deploy to current EC2 instance in stack

---

devops/cloudformation.json

In order to add the service tag to the EC2 volume, we need this property
This will help with cost tracking

Tag volumes of EC2 instances

---

README.md
devops/playbook.yml
src/util.py

Renames the rapid transit directory to not include the route or direction since they're not needed (also make using them on the dashboard harder)
Fixes #81 
When merging we'll want to rename the existing dirs, but we can always do it after for the older files
We don't _need_ gobble for rapid transit since we have LAMP but we should still have it in case LAMP ever goes down or proves to be unreliable, so we should make it easily readable by the dashboard

Rename all rapid output directory

---

src/constants.py

Fixes #77 
Based on the guidance given in #86 i *think* this is all thats needed? I seem to be seeing Mattapan events in the feed after adding this so I assume this is all I need to do

Add mattapan trolley ID to the list

---

src/disk.py
src/event.py
src/trip_state.py

This adds occupancy status and percentage where applicable into the output CSV. 
The motivation is that this data could be shown in the tooltip on the data dashboard, This could help users understand the level of crowding on that particular train, which may impact: 
1. Excessive dwell times due to overcrowding and door blockage issues
2. Buses departing sooner because they are at crush capacity
3. Other potential patterns of note

Added occupancy_status and occupancy_percentage

---

src/gobble.py

This Pull Request adds support for consuming Reset and Add events. Remove events only contain the vehicle id, so special handling is required to get all the information we need from those. 
Add events are treated the same as updates and reset events are treated as a list of updates. 
I also added some logging for event types so we can get a better idea of the distribution.

Added support for Reset and add events, added logging for event type
